---
- hosts: all
  become: true
  vars:
    # Change one, change the other :)
    WORDPRESS_VERSION: 5.9.1
    WORDPRESS_CHECKSUM: 15746f848cd388e270bae612dccd0c83fa613259
  tasks:
    - name: Update APT cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install base tool set
      apt:
        pkg:
          - vim
          - php
          - nginx
          - mariadb-server

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Check if a reboot is needed on all servers
      stat:
        path: /var/run/reboot-required
        get_md5: false
      register: reboot_required_file

    - name: Restart servers
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Clean local APT repository
      apt:
        autoclean: true
        autoremove: true

    - name: Start nginx
      systemd:
        name: nginx
        enabled: true
        state: started

    - name: Start nginx
      systemd:
        name: mariadb
        enabled: true
        state: started

    - name: Download WordPress
      get_url:
        url: https://wordpress.org/wordpress-{{ WORDPRESS_VERSION }}.tar.gz
        checksum: sha1:{{ WORDPRESS_CHECKSUM }}
        dest: /home/vagrant/wordpress-{{ WORDPRESS_VERSION }}.tar.gz
        owner: vagrant
        group: vagrant

    - name: Extract WordPress
      become: true
      become_user: vagrant
      unarchive:
        src: /home/vagrant/wordpress-{{ WORDPRESS_VERSION }}.tar.gz
        dest: /home/vagrant
        remote_src: true
        creates: /home/vagrant/wordpress/license.txt
        owner: vagrant
        group: vagrant

    - name: Link Nginx wp to vagrant wordpress
      file:
        src: /home/vagrant/wordpress
        dest: /var/www/wp
        owner: root
        group: root
        state: link

    - name: Copy default Nginx config
      copy:
        src: files/default
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: 0644

    - name: Copy wordpress Nginx config
      copy:
        src: files/wordpress
        dest: /etc/nginx/sites-available/wordpress
        owner: root
        group: root
        mode: 0644

    - name: Link wordpress in sites-enabled
      file:
        src: /etc/nginx/sites-available/wordpress
        dest: /etc/nginx/sites-enabled/wordpress
        remote_src: true
        owner: root
        group: root
        state: link

    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
