---
- hosts: all
  become: true
  vars:
    # Change one, change the other :)
    wordpress_version: 5.9.1
    wordpress_checksum: 15746f848cd388e270bae612dccd0c83fa613259
    mariadb_root_password: password
    wp_database: wordpressdb
    mariadb_wp_user: wordpressuser
    mariadb_wp_password: password
  tasks:
    - name: Update APT cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install base tool set
      apt:
        pkg:
          - vim
          - php
          - php-fpm
          - php-mysql
          - nginx
          - mariadb-server
          - mariadb-client
          - python3-pymysql

    - name: Update all packages to the latest version
      apt:
        upgrade: dist

    - name: Check if a reboot is needed on all servers
      stat:
        path: /var/run/reboot-required
        get_md5: false
      register: reboot_required_file

    - name: Restart servers
      reboot:
        msg: "Reboot initiated by Ansible for kernel updates"
        connect_timeout: 5
        reboot_timeout: 300
        pre_reboot_delay: 0
        post_reboot_delay: 30
        test_command: uptime
      when: reboot_required_file.stat.exists

    - name: Clean local APT repository
      apt:
        autoclean: true
        autoremove: true

    - include_tasks: wordpress.yml
    - include_tasks: nginx.yml
    - include_tasks: mariadb.yml
